@Echo Off
Echo Welcome to Tails2012tim OS!!!
echo ------------T-------a--------i------l------s------2---0-----1------2------t----i------m-----o-----s---
cls
echo ----T----------a--------------i---------l----s-----2------0-----1----2----t----i---m-----o---s
cls
Echo Tails2012tim OS
Echo beta 1 test version
Echo Thanks For useing Tails2012tim OS Beta 1 Test Verson!
Echo Starting up....
Echo Entering GUI.....
C:\Tailsos\Tailsos.exe
